services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /opt/jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d

volumes:
  jenkins_home:
